Repository toddeTV/zlig, pull requests merged in 2025-01, with the labels that each got.

#131 refactor: add consistent file extensions & VSCode configuration
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  eslint.config.js
  src/components/CameraAndControls.vue
  src/components/DistanceFog.vue
  src/components/Lights.vue
  src/components/VisualHelper.vue
  src/components/models/BuildArea.vue
  src/components/models/Island.vue
  src/components/models/Ocean.vue
  src/components/models/Waterfall.vue
  src/components/models/buildings/CarnationShop.vue
  src/components/models/buildings/Windmill.vue
  src/components/ui/layout/game/debug/DebugMenu.vue
  src/game-logic/buildings/index.ts
  src/main.ts
  tools/vite-plugin-gltf.ts
  vite.config.ts
Labels: p1-chore

#135 refactor: change naming convention for pinia stores & composables
  src/components/CameraAndControls.vue
  src/components/DistanceFog.vue
  src/components/GameEngine.vue
  src/components/Lights.vue
  src/components/VisualHelper.vue
  src/components/buildings/BuildingArea.vue
  src/components/buildings/behaviors/ConstructingBehavior.vue
  src/components/buildings/behaviors/ProducingBehavior.vue
  src/components/buildings/behaviors/UpgradingBehavior.vue
  src/components/models/Ocean.vue
  src/components/models/Waterfall.vue
  src/components/ui/layout/game/GameCanvas.vue
  src/components/ui/layout/game/debug/DebugMenu.vue
  src/components/ui/layout/game/sidebar/BuildingRow.vue
  src/components/ui/layout/game/sidebar/SelectedBuildingDetails.vue
  src/components/ui/layout/game/sidebar/SelectedBuildingInConstruction.vue
  src/components/ui/layout/game/sidebar/SelectedBuildingUpgrading.vue
  src/components/ui/layout/game/sidebar/SideBar.vue
  src/components/ui/layout/game/topbar/GameSpeedButton.vue
  src/components/ui/layout/game/topbar/TopBar.vue
  src/composables/useBuildingAreasStore.ts
  src/composables/useCalculatedLightsStore.ts
  src/composables/useDebugStore.ts
  src/composables/useGameStateStore.ts
  src/composables/useGameTimeStore.ts
  src/composables/useSelectedBuildingAreaStore.ts
  src/composables/useSunPositionStore.ts
  src/views/GameView.vue
Labels: p1-chore

#130 chore: update dependency versions & update documentation
  LICENSE.md
  README.md
  package.json
  pnpm-lock.yaml
Labels: p1-chore

#136 fix: island model distorted NGons & visual gaps
  src/assets/models/Island/Island.bin
  src/assets/models/Island/Island.gltf
Labels: p2-nice-to-have

#132 feat: add auto redirect for home & update footer (c) text & logic
  src/components/ui/layout/game/sidebar/SideBar.vue
  src/views/HomeView.vue
Labels: p2-nice-to-have

#127 fix: animate ambient animations based on the game time
  src/components/buildings/behaviors/ConstructingBehavior.vue
  src/components/buildings/behaviors/ProducingBehavior.vue
  src/components/buildings/behaviors/UpgradingBehavior.vue
  src/components/models/Ocean.vue
  src/components/models/Waterfall.vue
  src/components/models/buildings/Windmill.vue
  src/composables/useGameTimeStore.ts
  src/utils/WaterShader.ts
  src/utils/duration.ts
Labels: p3-minor

#137 feat: add GitHub sponsoring/ funding
  .github/FUNDING.yml
  README.md
Labels: p2-nice-to-have
